<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="editing\EditingModel.fs" />
    <Compile Include="editing\EditingEvent.fs" />
    <Compile Include="editing\EditingLogic.fs" />
    <Compile Include="document\DocumentModel.fs" />
    <Compile Include="document\DocumentEvent.fs" />
    <Compile Include="document\DocumentLogic.fs" />
    <Folder Include="Syntax\" />
    <Compile Include="syntax\SyntaxModel.fs" />
    <Compile Include="syntax\SyntaxEvent.fs" />
    <Compile Include="syntax\SyntaxLogic.fs" />
    <Folder Include="Navigation\" />
    <Compile Include="navigation\NavigationModel.fs" />
    <Compile Include="navigation\NavigationEvent.fs" />
    <Compile Include="navigation\NavigationLogic.fs" />
    <Compile Include="Diagnostics\DiagnosticsModel.fs" />
    <Compile Include="Diagnostics\DiagnosticsEvent.fs" />
    <Compile Include="Diagnostics\DiagnosticsLogic.fs" />
    <Folder Include="Core\" />
    <Compile Include="Core\CoreModel.fs" />
    <Compile Include="Core\CoreEvent.fs" />
    <Compile Include="Core\CoreLogic.fs" />
    <Folder Include="Document\" />
  </ItemGroup>

</Project>
