[book]
title = "Functor User Book"
authors = ["Functor contributors"]
language = "en"
src = "src"

[output.html]
default-theme = "navy"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/pocinho/functors"
